version: '2'
services:
  pio:
    build:
      context: .
    image: pio
    command: sleep 1000000
    ports:
      - "9000:9000"
      - "3000:3000"
      - "7070:7070"
    environment:
      PGSQL_URL: postgres://postgres:5432/pio
    depends_on:
      - postgres
  
  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_DB: pio
      POSTGRES_PASSWORD: pio
      POSTGRES_USER: pio
    ports:
      - "5432:5432"

